### ISSUE TITLE
Extreme HatsとExtreme Skinsへの実装について

### ISSUE THREAD

**Issue by yukieiji** [Ujet222/CustomCosmetic_YJ#2]
### 以下の2点について確認です

- こちらのスキンデータをそれぞれ[Extreme Hats](https://github.com/yukieiji/ExtremeHats)と[Extreme Skins](https://github.com/yukieiji/ExtremeVisor)で使用しても大丈夫でしょうか
- またTOR形式のものからデータ構造が大きく変わるためデータをリポジトリに上げ直す必要がありますが大丈夫でしょうか(このリポジトリのデータ自体がGNU General Public License v3.0なのでほぼ問題ないとは思いますが)

**Comment by Ujet222** [comment]
スキンデータ使用はOKです。
データの再アップも大丈夫です。

**Comment by yukieiji** [comment]
> スキンデータ使用はOKです。
データの再アップも大丈夫です。

ありがとうございます

あと一つだけ、ExtremeSkinsのデータの分け方は基本的に作者名で分けられてますが他の統一も含めて全て「YJ*白桜作」で問題ないでしょうか、それとも「YJ*(スキンパーツ名)/白桜コレクション」の方がいいですか？

**Comment by Ujet222** [comment]
前者のほうで問題ないです。(コレクション系の名称は名称をつけないといけないTORとかSNR用につけてます)

**Comment by yukieiji** [comment]
> 前者のほうで問題ないです。(コレクション系の名称は名称をつけないといけないTORとかSNR用につけてます)

承知しました

最後に一部のデータが(スキンパーツ)Name内に無い(madadesuka_adaptive？)のですが、これは使用しないで欲しいデータで間違いないでしょうか

**Comment by Ujet222** [comment]
madadesuka_adaptive(帽子名:まだですか?)は記述し忘れですね...
実装(できればネムプレも...)してもらえるとうれしいです。

**Comment by yukieiji** [comment]
> madadesuka_adaptive(帽子名:まだですか?)は記述し忘れですね...

承知しました、それも実装させていただきます

> 実装(できればネムプレも...)してもらえるとうれしいです。

ネームプレートの実装についても承知です(チケット作った時は無かったので・・・)

**Comment by yukieiji** [comment]
先程実装が完了したことを報告させていただきます(ハットは[ExtremeHat](https://github.com/yukieiji/ExtremeHats)、バイザーは[ExtremeVisor](https://github.com/yukieiji/ExtremeVisor)、ネームプレートは[ExtremeNamePlate](https://github.com/yukieiji/ExtremeNamePlate)にデータが置いてあります)
翻訳やデータに間違いがなければこのチケットをクローズさせていただきます

**Comment by Ujet222** [comment]
翻訳、データの間違いなどはありませんでした。ありがとうございました。
